-- HackTime integration: per-user OAuth token + a projects table.
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "hackatime_token" text;

CREATE TABLE IF NOT EXISTS "projects" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "name" text NOT NULL,
  "hackatime_projects" text[] NOT NULL DEFAULT '{}',
  "created_at" timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "idx_projects_user" ON "projects"("user_id");
