-- Reviewer hour deflation + covert review telemetry.
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "approved_hours" real;

CREATE TABLE IF NOT EXISTS "review_audits" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" bigint NOT NULL REFERENCES "projects"("id") ON DELETE CASCADE,
  "user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "reviewer" text NOT NULL,
  "verdict" text NOT NULL,
  "note" text NOT NULL DEFAULT '',
  "claimed_hours" real NOT NULL DEFAULT 0,
  "approved_hours" real,
  "repo_opened" boolean NOT NULL DEFAULT false,
  "demo_opened" boolean NOT NULL DEFAULT false,
  "repo_seconds" real NOT NULL DEFAULT 0,
  "demo_seconds" real NOT NULL DEFAULT 0,
  "total_seconds" real NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "idx_review_audits_project" ON "review_audits"("project_id");
CREATE INDEX IF NOT EXISTS "idx_review_audits_created" ON "review_audits"("created_at");
